name: Auto Test
on:
   # События, которые запускают jobs
  push:
    branches: [ "main" ]

# jobs запускаются параллельно, если не указана последовательность
jobs:
    test1:
      name: Ubuntu
      # Операционная система в виртуальной машине, в которой запускаются процессы
      runs-on: ubuntu-latest
        # Шаги
        steps:
        # Клонируем репозиторий на runner
      - name: Checkout code
        uses: actions/checkout@v3

        # Устанавливаем версию питона 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Run test
        run: python geometric_lib_test.ru -v
    test2:
      name: Windows
      # Операционная система в виртуальной машине, в которой запускаются процессы
      runs-on: windows-latest
        # Шаги
        steps:
        # Клонируем репозиторий на runner
      - name: Checkout code
        uses: actions/checkout@v3

        # Устанавливаем версию питона 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Run test
        run: python geometric_lib_test.ru -v
        
